// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: analyser_user_settings.proto

package analyserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyserSettingsService_UpsertUserSettings_FullMethodName = "/analyser.AnalyserSettingsService/UpsertUserSettings"
	AnalyserSettingsService_SetUserActive_FullMethodName      = "/analyser.AnalyserSettingsService/SetUserActive"
)

// AnalyserSettingsServiceClient is the client API for AnalyserSettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC-сервис, который поднимает analyser.
// Тг-бот выступает клиентом и дергает эти методы.
type AnalyserSettingsServiceClient interface {
	UpsertUserSettings(ctx context.Context, in *UpsertUserSettingsRequest, opts ...grpc.CallOption) (*UpsertUserSettingsResponse, error)
	SetUserActive(ctx context.Context, in *SetUserActiveRequest, opts ...grpc.CallOption) (*SetUserActiveResponse, error)
}

type analyserSettingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyserSettingsServiceClient(cc grpc.ClientConnInterface) AnalyserSettingsServiceClient {
	return &analyserSettingsServiceClient{cc}
}

func (c *analyserSettingsServiceClient) UpsertUserSettings(ctx context.Context, in *UpsertUserSettingsRequest, opts ...grpc.CallOption) (*UpsertUserSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertUserSettingsResponse)
	err := c.cc.Invoke(ctx, AnalyserSettingsService_UpsertUserSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyserSettingsServiceClient) SetUserActive(ctx context.Context, in *SetUserActiveRequest, opts ...grpc.CallOption) (*SetUserActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserActiveResponse)
	err := c.cc.Invoke(ctx, AnalyserSettingsService_SetUserActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyserSettingsServiceServer is the server API for AnalyserSettingsService service.
// All implementations must embed UnimplementedAnalyserSettingsServiceServer
// for forward compatibility.
//
// gRPC-сервис, который поднимает analyser.
// Тг-бот выступает клиентом и дергает эти методы.
type AnalyserSettingsServiceServer interface {
	UpsertUserSettings(context.Context, *UpsertUserSettingsRequest) (*UpsertUserSettingsResponse, error)
	SetUserActive(context.Context, *SetUserActiveRequest) (*SetUserActiveResponse, error)
	mustEmbedUnimplementedAnalyserSettingsServiceServer()
}

// UnimplementedAnalyserSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyserSettingsServiceServer struct{}

func (UnimplementedAnalyserSettingsServiceServer) UpsertUserSettings(context.Context, *UpsertUserSettingsRequest) (*UpsertUserSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserSettings not implemented")
}
func (UnimplementedAnalyserSettingsServiceServer) SetUserActive(context.Context, *SetUserActiveRequest) (*SetUserActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserActive not implemented")
}
func (UnimplementedAnalyserSettingsServiceServer) mustEmbedUnimplementedAnalyserSettingsServiceServer() {
}
func (UnimplementedAnalyserSettingsServiceServer) testEmbeddedByValue() {}

// UnsafeAnalyserSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyserSettingsServiceServer will
// result in compilation errors.
type UnsafeAnalyserSettingsServiceServer interface {
	mustEmbedUnimplementedAnalyserSettingsServiceServer()
}

func RegisterAnalyserSettingsServiceServer(s grpc.ServiceRegistrar, srv AnalyserSettingsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyserSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyserSettingsService_ServiceDesc, srv)
}

func _AnalyserSettingsService_UpsertUserSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUserSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyserSettingsServiceServer).UpsertUserSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyserSettingsService_UpsertUserSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyserSettingsServiceServer).UpsertUserSettings(ctx, req.(*UpsertUserSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyserSettingsService_SetUserActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyserSettingsServiceServer).SetUserActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyserSettingsService_SetUserActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyserSettingsServiceServer).SetUserActive(ctx, req.(*SetUserActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyserSettingsService_ServiceDesc is the grpc.ServiceDesc for AnalyserSettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyserSettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyser.AnalyserSettingsService",
	HandlerType: (*AnalyserSettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertUserSettings",
			Handler:    _AnalyserSettingsService_UpsertUserSettings_Handler,
		},
		{
			MethodName: "SetUserActive",
			Handler:    _AnalyserSettingsService_SetUserActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyser_user_settings.proto",
}
