// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: analyser_user_settings.proto

package analyserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Настройки пользователя, практически 1-в-1 с domain.UserSettings.
type UserSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChatId           int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	WatchFact        bool                   `protobuf:"varint,2,opt,name=watch_fact,json=watchFact,proto3" json:"watch_fact,omitempty"`
	WatchPotential   bool                   `protobuf:"varint,3,opt,name=watch_potential,json=watchPotential,proto3" json:"watch_potential,omitempty"`
	MinDiffFact      float64                `protobuf:"fixed64,4,opt,name=min_diff_fact,json=minDiffFact,proto3" json:"min_diff_fact,omitempty"`
	MinDiffPotential float64                `protobuf:"fixed64,5,opt,name=min_diff_potential,json=minDiffPotential,proto3" json:"min_diff_potential,omitempty"`
	MaxNotional      float64                `protobuf:"fixed64,6,opt,name=max_notional,json=maxNotional,proto3" json:"max_notional,omitempty"`
	IsActive         bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_analyser_user_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_user_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_analyser_user_settings_proto_rawDescGZIP(), []int{0}
}

func (x *UserSettings) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserSettings) GetWatchFact() bool {
	if x != nil {
		return x.WatchFact
	}
	return false
}

func (x *UserSettings) GetWatchPotential() bool {
	if x != nil {
		return x.WatchPotential
	}
	return false
}

func (x *UserSettings) GetMinDiffFact() float64 {
	if x != nil {
		return x.MinDiffFact
	}
	return 0
}

func (x *UserSettings) GetMinDiffPotential() float64 {
	if x != nil {
		return x.MinDiffPotential
	}
	return 0
}

func (x *UserSettings) GetMaxNotional() float64 {
	if x != nil {
		return x.MaxNotional
	}
	return 0
}

func (x *UserSettings) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Создать/обновить настройки пользователя.
type UpsertUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserSettingsRequest) Reset() {
	*x = UpsertUserSettingsRequest{}
	mi := &file_analyser_user_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserSettingsRequest) ProtoMessage() {}

func (x *UpsertUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_user_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_analyser_user_settings_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertUserSettingsRequest) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpsertUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserSettingsResponse) Reset() {
	*x = UpsertUserSettingsResponse{}
	mi := &file_analyser_user_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserSettingsResponse) ProtoMessage() {}

func (x *UpsertUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_user_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpsertUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_analyser_user_settings_proto_rawDescGZIP(), []int{2}
}

// Включить/выключить анализ для пользователя.
type SetUserActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserActiveRequest) Reset() {
	*x = SetUserActiveRequest{}
	mi := &file_analyser_user_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserActiveRequest) ProtoMessage() {}

func (x *SetUserActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_user_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserActiveRequest.ProtoReflect.Descriptor instead.
func (*SetUserActiveRequest) Descriptor() ([]byte, []int) {
	return file_analyser_user_settings_proto_rawDescGZIP(), []int{3}
}

func (x *SetUserActiveRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SetUserActiveRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type SetUserActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserActiveResponse) Reset() {
	*x = SetUserActiveResponse{}
	mi := &file_analyser_user_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserActiveResponse) ProtoMessage() {}

func (x *SetUserActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_user_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserActiveResponse.ProtoReflect.Descriptor instead.
func (*SetUserActiveResponse) Descriptor() ([]byte, []int) {
	return file_analyser_user_settings_proto_rawDescGZIP(), []int{4}
}

var File_analyser_user_settings_proto protoreflect.FileDescriptor

const file_analyser_user_settings_proto_rawDesc = "" +
	"\n" +
	"\x1canalyser_user_settings.proto\x12\banalyser\"\x81\x02\n" +
	"\fUserSettings\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"watch_fact\x18\x02 \x01(\bR\twatchFact\x12'\n" +
	"\x0fwatch_potential\x18\x03 \x01(\bR\x0ewatchPotential\x12\"\n" +
	"\rmin_diff_fact\x18\x04 \x01(\x01R\vminDiffFact\x12,\n" +
	"\x12min_diff_potential\x18\x05 \x01(\x01R\x10minDiffPotential\x12!\n" +
	"\fmax_notional\x18\x06 \x01(\x01R\vmaxNotional\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"O\n" +
	"\x19UpsertUserSettingsRequest\x122\n" +
	"\bsettings\x18\x01 \x01(\v2\x16.analyser.UserSettingsR\bsettings\"\x1c\n" +
	"\x1aUpsertUserSettingsResponse\"L\n" +
	"\x14SetUserActiveRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"\x17\n" +
	"\x15SetUserActiveResponse2\xcc\x01\n" +
	"\x17AnalyserSettingsService\x12_\n" +
	"\x12UpsertUserSettings\x12#.analyser.UpsertUserSettingsRequest\x1a$.analyser.UpsertUserSettingsResponse\x12P\n" +
	"\rSetUserActive\x12\x1e.analyser.SetUserActiveRequest\x1a\x1f.analyser.SetUserActiveResponseB\x1cZ\x1a/internal/proto/analyserpbb\x06proto3"

var (
	file_analyser_user_settings_proto_rawDescOnce sync.Once
	file_analyser_user_settings_proto_rawDescData []byte
)

func file_analyser_user_settings_proto_rawDescGZIP() []byte {
	file_analyser_user_settings_proto_rawDescOnce.Do(func() {
		file_analyser_user_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyser_user_settings_proto_rawDesc), len(file_analyser_user_settings_proto_rawDesc)))
	})
	return file_analyser_user_settings_proto_rawDescData
}

var file_analyser_user_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analyser_user_settings_proto_goTypes = []any{
	(*UserSettings)(nil),               // 0: analyser.UserSettings
	(*UpsertUserSettingsRequest)(nil),  // 1: analyser.UpsertUserSettingsRequest
	(*UpsertUserSettingsResponse)(nil), // 2: analyser.UpsertUserSettingsResponse
	(*SetUserActiveRequest)(nil),       // 3: analyser.SetUserActiveRequest
	(*SetUserActiveResponse)(nil),      // 4: analyser.SetUserActiveResponse
}
var file_analyser_user_settings_proto_depIdxs = []int32{
	0, // 0: analyser.UpsertUserSettingsRequest.settings:type_name -> analyser.UserSettings
	1, // 1: analyser.AnalyserSettingsService.UpsertUserSettings:input_type -> analyser.UpsertUserSettingsRequest
	3, // 2: analyser.AnalyserSettingsService.SetUserActive:input_type -> analyser.SetUserActiveRequest
	2, // 3: analyser.AnalyserSettingsService.UpsertUserSettings:output_type -> analyser.UpsertUserSettingsResponse
	4, // 4: analyser.AnalyserSettingsService.SetUserActive:output_type -> analyser.SetUserActiveResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analyser_user_settings_proto_init() }
func file_analyser_user_settings_proto_init() {
	if File_analyser_user_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyser_user_settings_proto_rawDesc), len(file_analyser_user_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyser_user_settings_proto_goTypes,
		DependencyIndexes: file_analyser_user_settings_proto_depIdxs,
		MessageInfos:      file_analyser_user_settings_proto_msgTypes,
	}.Build()
	File_analyser_user_settings_proto = out.File
	file_analyser_user_settings_proto_goTypes = nil
	file_analyser_user_settings_proto_depIdxs = nil
}
