// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tgbot_notifications.proto

package tgbotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Уведомление, которое analyser шлёт в tg-bot.
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`           // "fact" или "potential"
	Pair          string                 `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`           // "USDT/RUB", "USDT/A7A5"
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // "buy_rapira_sell_rapira" и т.п.
	ProfitDiff    float64                `protobuf:"fixed64,5,opt,name=profit_diff,json=profitDiff,proto3" json:"profit_diff,omitempty"`
	Notional      float64                `protobuf:"fixed64,6,opt,name=notional,proto3" json:"notional,omitempty"`
	OpHash        string                 `protobuf:"bytes,7,opt,name=op_hash,json=opHash,proto3" json:"op_hash,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // unix time в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_tgbot_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_tgbot_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Notification) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Notification) GetProfitDiff() float64 {
	if x != nil {
		return x.ProfitDiff
	}
	return 0
}

func (x *Notification) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *Notification) GetOpHash() string {
	if x != nil {
		return x.OpHash
	}
	return ""
}

func (x *Notification) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

// Запрос на отправку уведомления.
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_tgbot_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_tgbot_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_tgbot_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgbot_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_tgbot_notifications_proto_rawDescGZIP(), []int{2}
}

var File_tgbot_notifications_proto protoreflect.FileDescriptor

const file_tgbot_notifications_proto_rawDesc = "" +
	"\n" +
	"\x19tgbot_notifications.proto\x12\x05tgbot\"\xeb\x01\n" +
	"\fNotification\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1f\n" +
	"\vprofit_diff\x18\x05 \x01(\x01R\n" +
	"profitDiff\x12\x1a\n" +
	"\bnotional\x18\x06 \x01(\x01R\bnotional\x12\x17\n" +
	"\aop_hash\x18\a \x01(\tR\x06opHash\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\"R\n" +
	"\x17SendNotificationRequest\x127\n" +
	"\fnotification\x18\x01 \x01(\v2\x13.tgbot.NotificationR\fnotification\"\x1a\n" +
	"\x18SendNotificationResponse2o\n" +
	"\x18TgBotNotificationService\x12S\n" +
	"\x10SendNotification\x12\x1e.tgbot.SendNotificationRequest\x1a\x1f.tgbot.SendNotificationResponseB\x19Z\x17/internal/proto/tgbotpbb\x06proto3"

var (
	file_tgbot_notifications_proto_rawDescOnce sync.Once
	file_tgbot_notifications_proto_rawDescData []byte
)

func file_tgbot_notifications_proto_rawDescGZIP() []byte {
	file_tgbot_notifications_proto_rawDescOnce.Do(func() {
		file_tgbot_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tgbot_notifications_proto_rawDesc), len(file_tgbot_notifications_proto_rawDesc)))
	})
	return file_tgbot_notifications_proto_rawDescData
}

var file_tgbot_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tgbot_notifications_proto_goTypes = []any{
	(*Notification)(nil),             // 0: tgbot.Notification
	(*SendNotificationRequest)(nil),  // 1: tgbot.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 2: tgbot.SendNotificationResponse
}
var file_tgbot_notifications_proto_depIdxs = []int32{
	0, // 0: tgbot.SendNotificationRequest.notification:type_name -> tgbot.Notification
	1, // 1: tgbot.TgBotNotificationService.SendNotification:input_type -> tgbot.SendNotificationRequest
	2, // 2: tgbot.TgBotNotificationService.SendNotification:output_type -> tgbot.SendNotificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tgbot_notifications_proto_init() }
func file_tgbot_notifications_proto_init() {
	if File_tgbot_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tgbot_notifications_proto_rawDesc), len(file_tgbot_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tgbot_notifications_proto_goTypes,
		DependencyIndexes: file_tgbot_notifications_proto_depIdxs,
		MessageInfos:      file_tgbot_notifications_proto_msgTypes,
	}.Build()
	File_tgbot_notifications_proto = out.File
	file_tgbot_notifications_proto_goTypes = nil
	file_tgbot_notifications_proto_depIdxs = nil
}
