// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: tgbot_notifications.proto

package tgbotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TgBotNotificationService_SendNotification_FullMethodName = "/tgbot.TgBotNotificationService/SendNotification"
)

// TgBotNotificationServiceClient is the client API for TgBotNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Этот сервис поднимает tg-bot.
// Analyser реализует Notifier через gRPC-клиент к этому сервису.
type TgBotNotificationServiceClient interface {
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
}

type tgBotNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTgBotNotificationServiceClient(cc grpc.ClientConnInterface) TgBotNotificationServiceClient {
	return &tgBotNotificationServiceClient{cc}
}

func (c *tgBotNotificationServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, TgBotNotificationService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgBotNotificationServiceServer is the server API for TgBotNotificationService service.
// All implementations must embed UnimplementedTgBotNotificationServiceServer
// for forward compatibility.
//
// Этот сервис поднимает tg-bot.
// Analyser реализует Notifier через gRPC-клиент к этому сервису.
type TgBotNotificationServiceServer interface {
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	mustEmbedUnimplementedTgBotNotificationServiceServer()
}

// UnimplementedTgBotNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTgBotNotificationServiceServer struct{}

func (UnimplementedTgBotNotificationServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedTgBotNotificationServiceServer) mustEmbedUnimplementedTgBotNotificationServiceServer() {
}
func (UnimplementedTgBotNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeTgBotNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgBotNotificationServiceServer will
// result in compilation errors.
type UnsafeTgBotNotificationServiceServer interface {
	mustEmbedUnimplementedTgBotNotificationServiceServer()
}

func RegisterTgBotNotificationServiceServer(s grpc.ServiceRegistrar, srv TgBotNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTgBotNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TgBotNotificationService_ServiceDesc, srv)
}

func _TgBotNotificationService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgBotNotificationServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgBotNotificationService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgBotNotificationServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgBotNotificationService_ServiceDesc is the grpc.ServiceDesc for TgBotNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgBotNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tgbot.TgBotNotificationService",
	HandlerType: (*TgBotNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _TgBotNotificationService_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tgbot_notifications.proto",
}
